
<!DOCTYPE HTML>
<html>
<head>
<title>Terms and Conditions | Scopee</title>
<meta name="description" content="The provisions of these Terms of Service set out the terms and conditions that are applicable to everyone who accesses or uses the scopee website and network available at scopee.in">
 <!-- Include meta tag to ensure proper rendering and touch zooming -->
 <meta name="keywords" content="t&c,scopee t&c,scopee,scopee.in,terms and condition,scopee.in terms and condition, scopee terms and condition."/>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link type="text/css" rel="stylesheet" href="cssa/font-awesome.css">
  <link type="text/css" rel="stylesheet" href="cssa/material-design-iconic-font.css">
  <link type="text/css" rel="stylesheet" href="cssa/bootstrap.css">
  <link type="text/css" rel="stylesheet" href="cssa/animate.css">
  <link type="text/css" rel="stylesheet" href="cssa/layout.css">
  <link type="text/css" rel="stylesheet" href="cssa/components.css">
  <link type="text/css" rel="stylesheet" href="cssa/widgets.css">
  <link type="text/css" rel="stylesheet" href="cssa/plugins.css">
  <link type="text/css" rel="stylesheet" href="cssa/pages.css">
  <link type="text/css" rel="stylesheet" href="cssa/bootstrap-extend.css">
  <link type="text/css" rel="stylesheet" href="cssa/common.css">
  <link type="text/css" rel="stylesheet" href="cssa/responsive.css">
  <link type="text/css" id="themes" rel="stylesheet" href="">
  <link href="font-awesome/cssa/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link type="text/css" rel="stylesheet" href="css/font-awesome.css">
  <link type="text/css" rel="stylesheet" href="css/material-design-iconic-font.css">
  <link type="text/css" rel="stylesheet" href="css/bootstrap.css">
  <link type="text/css" rel="stylesheet" href="css/animate.css">
  <link type="text/css" rel="stylesheet" href="css/layout.css">
  <link type="text/css" rel="stylesheet" href="css/components.css">
  <link type="text/css" rel="stylesheet" href="css/widgets.css">
  <link type="text/css" rel="stylesheet" href="css/plugins.css">
  <link type="text/css" rel="stylesheet" href="css/pages.css">
  <link type="text/css" rel="stylesheet" href="css/bootstrap-extend.css">
  <link type="text/css" rel="stylesheet" href="css/common.css">
  <link type="text/css" rel="stylesheet" href="css/responsive.css">
  <link type="text/css" id="themes" rel="stylesheet" href="">
  <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
</head>
<body >
<?php require('inc/r-side-bar.php');?>
 
<div class="content" style="margin:10px;padding:5px; background-color: #ffffff;">
<h2>Terms of Service</h2>
<p>Date of Last Revision: May 28th, 2016 </p>
<p>The provisions of these Terms of Service set out the terms and conditions that are applicable to everyone who accesses or uses the scopee website and network available at scopee.in (the "Service"). By accessing and using the Service (or any portion of it), you are indicating your agreement to be bound by and to adhere to the following provisions, including any schedules, exhibits and related materials that are attached and/or incorporated by reference (collectively, the "Service Terms"). The Service Terms apply between you and the owner of the scopee website (the "Network Owner"). They also give certain directly enforceable rights to the business that provides the Network Owner with technology infrastructure and hosting services for the Service (the "Technology Licensor"), although there is no direct contractual relationship between you and the Technology Licensor in relation to the Service.</p>
<p>The Network Owner expressly reserves the right to amend and otherwise modify the Service Terms (or any portion thereof) periodically without advance notice. Please check the Service Terms each time that you use the Service to ensure that you are aware of any changes to the Service Terms. The posted Service Terms will indicate the date on which they were last updated. Your continued use of the Service after the adoption and/or implementation of any such changes shall be deemed to indicate your acceptance and agreement with any and all such amendments and/or modifications. If you do not agree with any particular changes to the Service Terms and/or to the Service, your only remedy is not to use the Service and to cancel the account(s) for which you previously signed-up.</p>
<p>If there is a conflict between these Service Terms and any other policies, rules, regulations or guidelines posted on the Service, the Network Owner shall resolve such conflict in its sole discretion. Any questions about the Service Terms should be put to the Network Owner from the membership area via a private message.</p>
<h2>To Become a Member of the Network</h2>
<p>1.	You must be 13 years or older to create an Account that will entitle you to use the Service. <br>
2.	You must provide your name, a valid email address, and any other information requested during sign-up in order to complete the registration process. You may from time to time be required to provide further contact and other information as a condition of continuing use of part(s) or all of the Service. <br>
3.	You must update any information provided immediately if it becomes inaccurate and must ensure that the email address in your Account information is at all times a valid address at which you can be contacted. <br>
4.	You must not provide any false or inaccurate information whether during the registration process or otherwise. <br>
5.	Accounts must not be registered by a "bot" or any other automated process or method. <br>
6.	You will need to create a log-in name and a password in order to establish an Account. You must not use a log-in name that is also being used by anyone else, and your log-in name must not be vulgar, offensive or otherwise objectionable, as determined by the Network Owner or its Technology Licensor at their sole discretion. Protecting your Account and preserving the security of your password is your responsibility. The Network Owner shall have no obligation or liability to you or any third party for any loss or damage resulting from your failure to maintain adequate protection for your Account, log-in name and/or password.<br> 
7.	Only one person may use a log-in. Stated differently, a single login must not be shared by multiple users. <br>
8.	An Account may not be transferred or converted to a new Account. However, an Account can be upgraded, for a separate charge, in order to obtain premium features and/or functionality that the Network Owner may choose to make available to you. <br>
9.	Notwithstanding any of the above, you acknowledge and agree that the Service Terms will apply to anyone that you authorize, allow or otherwise permit to use your Account, user ID and/or password that you create, and, moreover, that you will be personally responsible and solely liable for the consequences, including the potential termination of your Account(s), that may result if any such person(s) violates any of the provisions of the Service Terms. </p>
<h2>Payments</h2><p>
1.	You are responsible for all of the charges that are incurred as a result of your use of the Service, including, without limitation, any applicable taxes, as well as for all purchases made by you or anyone else that you authorize, allow or otherwise permit to access and use your Account(s) and/or any web page(s) or content that relates to your Account(s). You are also responsible for any Internet service provider charges, as well as for any telephone, wireless and/or other connection fees that you may incur when accessing and using the Service. </p>
<h2>Service Changes</h2><p>
1.	The Network Owner reserves the right at any time and from time to time to modify, change, suspend or discontinue, temporarily or permanently, the Service (or any part thereof) with or without prior notice to you or any third party. <br>
2.	Any new modifications that alter, change, improve, enhance, augment, or otherwise modify the then-current Service, including, but not limited to, the release of new tools, utilities, resources, features or functionality, shall be subject to the Service Terms. <br>
3.	Notice of any change(s) to the Service may be provided by the Network Owner (or its representatives) at any time and from time to time by posting notice of the applicable change(s) to the Service website. Notice of any change(s) to the Service may be provided by the Network Owner (or its representatives) at any time and from time to time by posting notice of the applicable change(s) to the Service website. <br>
4.	You acknowledge and agree that the cancellation of your Account(s) and service(s) hereunder is your sole right and exclusive remedy with respect to any dispute that you may have that relates in any manner to the Service, including, without limitation, any dispute arising from or in connection with (i) the Service Terms or any of the Network Owner's or the Technology Licensor's policies, rules, regulations, or guidelines relating to the Service; (ii) your ability or inability to access and/or use the Service; and (iii) the content (including, without limitation, any related data and information) displayed or otherwise made available as part of or otherwise in connection with the Service. </p>
<h2>Ownership of Service and User-Generated Content</h2>
<p>
1.	The Network Owner and its licensors own and/or otherwise control all rights, title and interests in and to the Service, including, without limitation, any and all copyrights, trademarks, patents, and all other intellectual property and other proprietary rights relating to the Service (collectively, the "Proprietary Rights"). The underlying computer programs comprising the Service, as well as the look and feel of the Service, are copyrighted by the "Technology Licensor" and any and all rights therein and thereto are expressly reserved by Bright Things Plc. These rights are protected by U.K. and international intellectual property laws, statutes and regulations. You acknowledge and agree that you will not duplicate, reproduce, copy, alter, adapt, prepare any derivative work, modify, perform or display (publicly or otherwise), distribute, or otherwise use or exploit the Service (or any part thereof) or any portion of the HTML/CSS, user interface and/or other audio-visual design elements relating to the Service (except in accordance with the terms and subject to the conditions referenced in the Service Terms) without the Technology Licensor's prior written consent. <br>
2.	The Network Owner hereby grants you, effective upon completion of registration of an Account that entitles you to access and use the Service, a personal, limited, non-exclusive, non-sublicensable, non-transferable, revocable right and privilege, under the applicable Proprietary Rights, to<br> 
(i) reproduce and use the object code version of the computer software that underlies, comprises and enables the Service (the "Service Software") solely for the purpose of accessing, creating, posting and otherwise using the Service and the social networks that are created with the Service Software and that are made available as part of the Service to registered users and other individuals who access and use the Service, and <br>
(ii) to reproduce, publicly display and distribute, but solely as part of the Service, the particular content made available by the Network Owner in conjunction with the Service, all in accordance with the terms and subject to the conditions of the Service Terms and such separate policies, rules, regulations and guidelines (if any) applicable to such content. Please be advised that neither the Network Owner nor the Technology Licensor nor any of their affiliates grants you or any third party any rights or interests with respect to any content that are authored, created or made available by any other registered users or other individuals who access and use the Service. <br>
3.	For the avoidance of doubt, the Network Owner claims no intellectual property rights with respect to any of the content that you elect to provide to the Service, including your profile and any materials you voluntarily elect to upload to the Service and/or to the web pages that you create that are associated with your registered Account(s). However, by choosing to make your web pages and related content available on the Service in a form that is intended to be shared publicly, you hereby grant to the Network Owner, the Technology Licensor and their affiliates a non-exclusive license (with rights of sublicense) to reproduce, prepare derivative works, publicly display, publicly perform, and distribute any and all such web pages and content as part of the Service, and you agree to allow all registered users and other individuals who access and use the Service, to access, view, reproduce, publicly display, publicly perform, comment upon, review, share, and otherwise use and distribute your web pages and related content (or any portions of any of the foregoing) as part of or otherwise in connection with the Service. Similarly, where you choose an option in the Service that allows you to make your web pages and related content available on the Service to be shared in a non-public context as part of the Service, you hereby grant to the Network Owner, the Technology Licensor and their affiliates a non-exclusive license (with rights of sublicense) to reproduce, prepare derivative works, display, perform, and distribute any and all such web pages and related content as part of the Service on the applicable non-public basis. <br>
4.	You acknowledge that neither the Network Owner nor the Technology Licensor pre-screens any of the various content and materials (including, without limitation, any related data and information) submitted and posted on and/or as part of the Service by you or any of the other individuals or entities that elect, at their discretion, to access and/or use the Service (whether or not registered with the Service) or any third-party advertisers that have a contract for the marketing and advertising of any third-party products or services by means of the Service. You agree that neither the Network Owner nor the Technology Licensor shall have any obligations or responsibilities, nor any liability of any kind or nature, with respect to any such content or materials, and the Network Owner hereby expressly disclaims any obligation on the part of it or the Technology Licensor to monitor and all liabilities with respect to any such content or materials that do not originate with the Network Owner or the Technology Licensor respectively. <br>
5.	The Network Owner expressly reserves the right, at all times and at its sole discretion, to quarantine, remove, delete and/or refuse to continue to allow to be displayed and distributed on or as part of the Service any web page(s), any content or materials and/or related data or information relating to your Account(s) that is made available via the Service to interested users (whether or not registered with the Service), such as, for example, and not as a limitation upon the generality of the foregoing, any content or materials that the Network Owner or the Technology Licensor believe may violate the rights of any third party or contravene any of the terms or conditions referenced in the Service Terms. <br>
6.	The Network Owner further reserves the right for it and the Technology Licensor, at all times and at their sole discretion, to access, read, preserve and disclose any and all content or materials (including, without limitation, any related data and information) that either of them believes is necessary or that would facilitate (i) compliance with any applicable law, statute, regulation, legal process or governmental request; (ii) the enforcement of the Service Terms, including, without limitation, the investigation of any apparent or perceived breach or default hereunder; (iii) the detection, prevention, and/or other efforts to address any apparent or perceived misrepresentation, fraud, security issue or technical matter; (iv) the investigation or other efforts to respond to any customer or other user support request; (v) any efforts to secure and/or protect any of the rights, title and interests of the Technology Licensor relating to the Service (including, without limitation, the API), and safeguarding the property and protecting the safety and security of the Technology Licensor, its users (whether or not registered with the Service) and the public. </p>
<h2>Online Conduct for Network Owners and Members</h2><p>
1.	Online conduct should be guided by common sense and respect for other users (whether or not registered with the Service) and for the employees and representatives of the Network Owner and the Technology Licensor, as well as respect for the laws, statutes and regulations that would apply to ones conduct in the real (i.e., offline) world. Inappropriate behaviour or illegal activities identified on and/or in connection with the Service will not be tolerated. Please be advised that we will terminate the Account(s) of anyone who engages in inappropriate behaviour or illegal activity on and/or in connection with the Service, and we and the Technology Licensor shall be free to cooperate with law enforcement officials with respect to any illegal activities or actionable conduct.<br> 
2.	You acknowledge and agree that you will be personally responsible for your use of the Service and for all of your communications and activities on and/or in connection with the Service, including, without limitation, any and all content and materials (including, without limitation, any related data and information) that you or any third-party users using your Account(s) ("Third Party Users") contribute to the Service (whether alone or in collaboration with others). <br>
3.	You will violate the Service Terms if you or any Third-Party Users do any of the following:<br>
1.	Copy, reproduce, duplicate, upload, post, host, display or perform (publicly or otherwise), market, advertise, promote, distribute, transmit, or otherwise disseminate any of the following types of Content Materials (including, without limitation, any related data or information).<br> 
2.	that are illegal or otherwise promote or encourage any illegal activity (including, without limitation, hacking, cracking, or the distribution of counterfeit software, or any products or services derived from any such activities; or 
3.	that you do not own or have permission to freely distribute; or that violates any indecency laws. <br>
4.	that violates any laws or regulations worldwide. <br>
5.	Engage in any activity in connection with the Service that violates any laws or regulations worldwide, including without limitation laws as to indecency, child protection, extreme pornographic images, race hatred and terrorism. <br>
6.	Copy, reproduce, duplicate, upload, post, host, cause to be displayed or performed (publicly or otherwise), distribute, transmit, or otherwise disseminate any unsolicited email, SMSs, or "spam" messages .<br>
7.	Copy, reproduce, duplicate, upload, post, host, cause to be displayed or performed (publicly or otherwise), distribute, transmit, or otherwise disseminate any worms, viruses, corrupted data, or any other such code of a destructive nature (aka, malware) .<br>
8.	Modify any part of the Service or any web site(s) related to the Service that the Technology Licensor has not expressly authorized you in writing to modify.<br> 
9.	Hack into, adapt, or otherwise modify the Service (or any part thereof) and/or any other website so as to falsely imply that it is associated with the Service or the Technology Licensor (or any of its affiliates), or any products or services of Technology Licensor (or any of its affiliates), <br>
10.	Hack into, decipher, adapt, modify or otherwise attempt to interfere with any transmissions to or from any of the servers that are used to operate the Service <br>
11.	Copy, reproduce, duplicate, offer to sell, sell, resell or otherwise exploit any portion of the Service, or any access or use of the Service, without the prior written consent of the Network Owner, in the case of Proprietary Rights owned or controlled by it, or the Technology Licensor, in all other cases (which consent may be granted or withheld at the relevant entity's sole and absolute discretion) .<br>
12.	Harass, threaten, intimidate, embarrass, disparage, or do anything else to any other user (whether or not registered with the Service) or guest of the Service that is offensive, unwarranted or unwanted (as determined by the Network Owner, at its sole discretion) .<br>
13.	Exploit any vulnerability, "bug", or other programming error in the Service Software or the Service, or communicate the existence of any such matter, either directly or indirectly, to any other user (whether or not registered with the Service) or guest of the Service.<br> 
14.	Claim or pretend to be an employee or representative of the Network Owner or the Technology Licensor (or any of their affiliates) or take any action that would imply that you have any such relationship with any of the foregoing, or impersonate any other person, including, without limitation, any celebrity, professional athlete, or other individual of public renown .<br>
15.	Attempt to obtain any password or other Account information, or any other private information, regarding any other user (whether or not registered with the Service) or guest of the Service .<br>
16.	Post messages or other correspondence for any purpose other than personal communications, such as, for example, any advertising, marketing or promotional materials regarding illegal gambling activities, chain letters, pyramid schemes, or that otherwise attempt to implement any unauthorized or illegal commercial use of the Service .<br>
17.	Disrupt the flow of conversations in chat rooms with, for example, vulgar or abusive language, excessive "shouting" in ALL CAPS, "spamming", "flooding" (i.e., posting repetitive text) or inputting large images that result in any displayed audiovisual work and/or related data or information appearing to move by too fast to be read by other participants in a chat room .<br>
18.	Post or otherwise disseminate within the Service or through any web site(s) that are part of the Service or outside of the Service any real-world personal information regarding any other user (whether or not registered) or any guest of the Service .<br>
19.	Use any features or functionality that are part of the Service (e.g., complaint buttons or customer service request forms) to make any false report to any employees or representatives of the Network Owner or the Technology Licensor (or any of their affiliates) .<br>
20.	Intentionally do anything that interferes with the opportunity or ability of any other user (whether or not registered with the Service) or guest of the Service to enjoy the features and functionality of the Service in accordance with the Service Terms, and/or that materially increases the costs or expenses of implementing, operating, administering, supporting and/or maintaining the Service (or any part thereof) .<br>
21.	Violate the Service Terms applicable to any other social network for which the Technology Licensor provides services. <br>
1.	The Network Owner expressly reserves the right (but without any obligation) to remove any content and/or materials and terminate any Account (as applicable) that contains any content, data and/or information that either it or the Technology Licensor determines, in its sole discretion, to be illegal, unlawful, harassing, threatening, intimidating, or an infringement of any third partys intellectual property rights or other proprietary rights, or a violation of any of the terms or conditions referenced in the Service Terms or any policies, rules, regulations or guidelines adopted by the Network Owner or the Technology Licensor or their affiliates (as applicable), at its/their sole discretion.<br> 
2.	If the Network Owner or the Technology Licensor or their affiliates (as applicable) determine that the use of any third-party widgets or any other such content or materials that are made available on the Service interfere with the operation, performance and/or functionality of the Service, they will have the right to suspend the Service and/or your Account and/or to allow you the opportunity to correct and remedy the noted problem to their reasonable satisfaction. 
3.	Harassment, intimidation or disparaging comments (whether verbally or in writing) or other abusive conduct or communications (including threats of abuse or retribution) directed at the Network Owner or the Technology Licensor (or any of its affiliates), or any of the officers, directors, employees, members, licensors, customers, agents or representatives of the foregoing, will result in immediate Account termination without advance notice and without any obligation or liability to the owner of such Account(s) or any third party. <br>
4.	Please be advised that if you violate the Service Terms, the Network Owner may issue a warning to you regarding your violation, or, alternatively, at its sole discretion, may elect to suspend or terminate any and all Accounts that you have established. You acknowledge and agree that the Network Owner is not required to provide you with any form of written or verbal notice before suspending or terminating your Account(s), although it may choose to do so, at its sole discretion. 

</p>
<h2>Disclaimer of Warranties Relating to the Service</h2><p>
1.	The Service is provided on an "as is" and "as available" basis, without any warranties of any kind, including, without limitation, any implied warranties of merchantability, fitness for any particular purpose, title, or non-infringement. You acknowledge and agree that your use of the Service (or any part thereof) is entirely at your sole risk and expense. <br>
2.	The Network Owner does not guarantee or warrant that (i) the Service will be uninterrupted, timely provided, secure, or error-free; (ii) the results that may be obtained from any use of the Service will be accurate, complete or reliable; (iii) the Service will meet your expectations or specific requirements; (iv) the quality of any products, services, information, or other materials purchased or otherwise obtained by you through the Service will meet your expectations; or (v) any errors confirmed to exist in the Service will be corrected. <br>
3.	<h5>TO THE MAXIMUM EXTENT PERMITTED UNDER APPLICABLE LAW, NEITHER THE NETWORK OWNER NOR ANY OF ITS AFFILIATES, NOR ANY OF THE OFFICERS, DIRECTORS, EMPLOYEES, MEMBERS, LICENSORS, CUSTOMERS, AGENTS OR REPRESENTATIVES OF THE NETWORK OWNER OR ANY OF ITS AFFILIATES, SHALL HAVE ANY LIABILITY OF ANY KIND OR NATURE IN CONNECTION WITH YOUR USE OF THE SERVICE (INCLUDING, WITHOUT LIMITATION, ANY LIABILITY FOR ANY DAMAGE TO YOUR COMPUTER HARDWARE AND/OR SOFTWARE), AND THE ENTIRE COST AND RISK OF YOUR USE OF THE SERVICE AND/OR INABILITY TO USE THE SERVICE (INCLUDING, WITHOUT LIMITATION, ANY DAMAGE TO YOUR REAL OR PERSONAL PROPERTY, INCLUDING, WITHOUT LIMITATION, YOU COMPUTER HARDWARE AND/OR SOFTWARE) RESIDES SOLELY AND EXCLUSIVELY WITH YOU. </h5><br>
4.	You expressly acknowledge and agree that neither the Network Owner (or any of its affiliates) nor any of the officers, directors, employees, members, licensors, customers, agents or representatives of the Network Owner (or any its affiliates) shall be liable for any direct, indirect, incidental, consequential, special, punitive or exemplary damages, including, but not limited to, damages for loss of sales, revenues, profits, use, data, goodwill, or any other tangible or intangible losses (even if the Network Owner has been advised of the possibility of any such loss or damages), resulting from: (i) your use or any inability to use the Service; (ii) the cost of procurement of substitute goods and/or services resulting from any goods, data, information or services purchased or obtained, or messages received, or transactions entered into, by means of or otherwise in connection with the Service; (iii) any unauthorized access to or alteration of your user or Account data or related information, or any content or materials, postings, communications, transmissions, or any related data or information; (iv) any conduct, statements, representations, or content or materials of any third party contained within or otherwise displayed on or as part of the Service; (v) the suspension, cancellation or termination of your Account(s); or (vi) any other matter(s) relating to the Service or the Service Terms. <br>
5.	You acknowledge that the technical processing and transmission of the Service, including your user and Account data, content and materials, and related data and information (a) may be distributed in an unencrypted form, (b) may involve transmissions by means of various networks and equipment that are not owned or controlled by the Network Owner, and (c) may require adaptive changes to conform to technical requirements of any connecting networks and/or devices, and you agree that the Network Owner shall have no obligation or liability to you or any third party as a result of or otherwise in connection with any such matters. <br>
6.	You further acknowledge that the Network Owner contracts with third parties to provide the necessary hardware, software, networking, storage, hosting, and related technology required to operate, manage, maintain and support the Service, including, without limitation, the posting, hosting and serving of your content and materials (including, without limitation, any related data and information), and you agree that the Network Owner shall have no obligation or liability to you or any third party as a result of or otherwise In connection with any such matters. <br>
7.	You further acknowledge and agree that, upon request by the Network Owner, you shall defend, indemnify and hold harmless the Network Owner and the Technology Licensor (and their affiliates) and the officers, directors, employees, members, licensors, customers, representatives and agents of the foregoing from and against any and all claims, losses, liabilities, damages, costs and expenses (including, without limitation, reasonable fees for attorneys and other professionals) resulting from or arising in connection with any breach of the Service Terms by you or any Third-Party Users that you authorize, allow or otherwise permit to have access to and/or to use any of your Account(s), user ID(s), and/or password(s), or that arise as a consequence of any content or materials (including, without limitation, any related data or information) posted, distributed or otherwise disseminated as part of or otherwise in connection with the Service and/or any Account(s) that you establish with the Service. <br>
8.	The Network Owner expressly reserves the right for the Technology Licensor, at its own expense, to participate in the defense of any claim, demand or suit for which you are obliged to indemnify the Technology Licensor hereunder, using counsel chosen by the Technology Licensor, and may assume control of its defense at any time, at the Technology Licensor's sole discretion. </p>
<h2>Third-Party Sites</h2><p>
1.	If you elect to click on a link within the Service or a link within any web page(s) that are displayed or performed on and/or as part of the Service, you will leave the Service and be directed to the website(s) that you choose to visit and voluntarily select, at your sole discretion. Please be advised that the Network Owner does not and cannot control the activities of any such third-party website operators, and, accordingly, the Network Owner does not know and cannot guarantee that any such third parties adhere to the same privacy and security practices as those adopted by the Network Owner. You should carefully review the privacy policies of the owners and/or operators of any such third-party website(s) that you elect to access and/or from which you request products or services, or to which (or from which) you transmit (or receive) any data or information. <br>
2.	Some third-party websites may charge separate fees (which are not included in any subscription or other payment plan that you choose to establish with the Network Owner). Any separate obligations, including, but not limited to, any fees or charges that you may incur as a result of your communications, dealings and/or transactions with any such third parties are solely and exclusively your responsibility. </p>
<h2>Advertising within the Service</h2><p>
1.	The Network Owner expressly reserves the right to include or permit the inclusion of advertisements, promotional announcements, sponsorships, and other such marketing materials and information (whether promoting third party products, the Network Owner, the Technology Licensor or otherwise) both within the Service, in general, and/or within the web page(s) and/or other elements that are made available to individuals who access and use the Service (whether or not registered with the Service). <br>
2.	The Network Owner may also incorporate technology for displaying dynamic advertising within the Service, which technology enables advertisements and promotional announcements to be temporarily uploaded into portions of the computer code for the Service (and into the applicable web page(s) that are part of the Service) that is reproduced and stored on your PC to be dynamically changed while you a web page(s) that are part of the Service. <br>
3.	You acknowledge and agree that all commercial aspects of the Service, including, without limitation, the display or performance of any static and/or dynamic advertising may be undertaken by the Network Owner and the Technology Licensor and their affiliates (as applicable), at its/their sole discretion, and that you have no expectation that advertisements, promotional announcements, sponsorships, and/or any other such marketing materials and information will not be incorporated within the Service and/or within the web page(s) that are made available as part of the Service. <br>
4.	The servers used in relation to the Service and/or those of any third-party advertisers or advertising providers, may be located outside your country of residence. If you reside in a Member State of the European Union, the servers may be located outside of the European Union.</p> 
<h2>Technology Licensor's Directly Enforceable Rights</h2><p>
1.	While there is no direct contractual relationship between you and the Technology Licensor, the Technology Licensor shall be entitled pursuant to the Contracts (Rights of Third Parties) Act 1999: (a) to enforce directly any provisions of these Service Terms which give rights to it; and (b) to exercise any or all rights of the Network Owner under these Service Terms and to enjoy all benefits, entitlements, licences, disclaimers of obligations and exclusions and limitations of liability granted to the Network Owner under these Service Terms as if it were named in place of the Network Owner. <br>
2.	Further, the Network Owner shall be entitled at any time and without your consent to assign or sub-contract to the Technology Licensor any rights under these Service Terms or to have the Technology Licensor exercise such right(s) on its behalf. </p>
<h2>General Provisions</h2><p>
1.	The delay or failure of the Network Owner to exercise or enforce any right, power or remedy under the Service Terms shall not constitute a waiver of such right, power or remedy. No waiver of any provision of these Service Terms shall be effective unless in writing and signed by the Network Owner. Any waiver by the Network Owner of any provision of the Service Terms shall not be construed as a waiver of any other provision of the Service Terms, nor shall such waiver operate as or be construed as a waiver of such provision respecting any future or subsequent event or circumstance. <br>
2.	The Service Terms constitute the entire agreement between you and the Network Owner with respect to your access to and use of the Service, for all intents and purposes, and supersede all prior and contemporaneous understandings and agreements between you and the Network Owner and any predecessor entity (including where applicable the Technology Licensor), including, but not limited to, any and all prior versions of the Service Terms. <br>
3.	You acknowledge and agree that the Service Terms (including, without limitation, any policies, rules, regulations and guidelines of or concerning the Service expressly incorporated by reference within the Service Terms) are not intended to confer and do not confer any rights, powers or remedies upon any person or entity other than you and the Network Owner, who are the parties to this Agreement, except that specific rights are granted to the Technology Licensor as set out above. <br>
4.	Nothing contained herein shall in any way constitute any association, partnership or joint venture between you and the Network Owner, or between the Network Owner and any other users (whether or not registered with the Service) or guests of the Service, or be construed to evidence the intention of the parties to establish any such relationship. Each of the parties shall be operating as independent contractors in fulfilling their respective obligations hereunder. No user (whether or not registered with the Service) or guest of the Service shall have the right, power or authority to make any representation or warranty (whether express or implied), or to assume or create any obligation on behalf of the Network Owner, or to bind the Network Owner in any manner whatsoever. <br>
5.	If any provision of the Service Terms (or part thereof) is determined by a court of competent jurisdiction to be void, invalid or otherwise unenforceable, such provision (or part thereof) shall be enforced to the extent possible consistent with the stated intention of the parties, or, if incapable of such enforcement, shall be deemed to be deleted from the Service Terms, while the remainder of the Service Terms shall continue in full force and remain in effect according to its stated terms and conditions. <br>
6.	The Service Terms shall be fairly interpreted in accordance with their stated terms and conditions, and without any strict construction in favor of or against either party. <br>
7.	The international laws (excluding its conflicts of law rules) shall govern the interpretation and enforcement of the Service Terms (as may be modified and otherwise amended by the Network Owner from time to time) and your access to and/or use of (or any inability to use) the Service. You expressly acknowledge and agree that exclusive jurisdiction for any claims or dispute with the Network Owner (or any of its affiliates), or relating in any manner to any of your Account(s) and/or to your access to and use of (or any inability to use) the Service shall be in the Courts of England, and you further agree and expressly consent to the exercise of personal jurisdiction in the Courts of England in connection with any such dispute, including, without limitation, any claims involving the Network Owner or the Technology Licensor (or any of their affiliates) or any of the officers, directors, employees, members, licensors, customers, representatives, agents, successors and assigns of any of the foregoing. 

</p>
<br><br>
	</div>
	<?php require("inc/footer.inc.php");?>
	<script src="js/lib/jquery.js"></script>
<script src="js/lib/jquery-migrate.js"></script>
<script src="js/lib/bootstrap.js"></script>
<script src="js/lib/jquery.ui.js"></script>
<script src="js/lib/jRespond.js"></script>
<script src="js/lib/nav.accordion.js"></script>
<script src="js/lib/hover.intent.js"></script>
<script src="js/lib/hammerjs.js"></script>
<script src="js/lib/jquery.hammer.js"></script>
<script src="js/lib/jquery.fitvids.js"></script>
<script src="js/lib/scrollup.js"></script>
<script src="js/lib/smoothscroll.js"></script>
<script src="js/lib/jquery.slimscroll.js"></script>
<script src="js/lib/jquery.syntaxhighlighter.js"></script>
<script src="js/lib/velocity.js"></script>
<script src="js/lib/jquery-jvectormap.js"></script>
<script src="js/lib/jquery-jvectormap-world-mill.js"></script>
<script src="js/lib/jquery-jvectormap-us-aea.js"></script>
<script src="js/lib/smart-resize.js"></script>
<!--iCheck-->
<script src="js/lib/icheck.js"></script>
<script src="js/lib/jquery.switch.button.js"></script>
<!--CHARTS-->
<script src="js/lib/chart/sparkline/jquery.sparkline.js"></script>
<script src="js/lib/chart/easypie/jquery.easypiechart.min.js"></script>
<script src="js/lib/chart/flot/excanvas.min.js"></script>
<script src="js/lib/chart/flot/jquery.flot.min.js"></script>
<script src="js/lib/chart/flot/curvedLines.js"></script>
<script src="js/lib/chart/flot/jquery.flot.time.min.js"></script>
<script src="js/lib/chart/flot/jquery.flot.stack.min.js"></script>
<script src="js/lib/chart/flot/jquery.flot.axislabels.js"></script>
<script src="js/lib/chart/flot/jquery.flot.resize.min.js"></script>
<script src="js/lib/chart/flot/jquery.flot.tooltip.min.js"></script>
<script src="js/lib/chart/flot/jquery.flot.spline.js"></script>
<script src="js/lib/chart/flot/jquery.flot.pie.min.js"></script>
<!--Forms-->
<script src="js/lib/jquery.maskedinput.js"></script>
<script src="js/lib/jquery.validate.js"></script>
<script src="js/lib/jquery.form.js"></script>
<script src="js/lib/j-forms.js"></script>
<script src="js/lib/jquery.loadmask.js"></script>
<script src="js/lib/vmap.init.js"></script>
<script src="js/lib/theme-switcher.js"></script>
<script src="js/apps.js"></script>
</body>
</html>